### ISSUE TITLE
Need to copy the footer from api.consentreceipt.org and past on api.consentreceipt.org

### ISSUE THREAD

**Issue by smartopian** [OpenConsent/ConsentReceipt#1]
Hi @dazzaji could you by chance tell me how to copy the footer from api.consentreceipt.org to consentreceipt.org?

**Comment by dazzaji** [comment]
Mark - Yes, we can talk about how to change the footer but let me set your expectations w/r/t the timing.   Given the footer content change is a new idea, the item was not in any issue or site description in the scope of work, the footer on the Mid-Project review was approved and has not changed and we only have a few hours to go before final delivery...please consider this project to be in a "code freeze" mode at this time.  

Moving forward, I recommend you close this issue and identify the handful of next phase developer site updates needed and then post issues for each change at one time.  Keep in mind that the changes, considered holistically, may involve format/display/structure and other interdependencies that would alter how the footer is generated, appears or operates. 

Keep this repository clean and easy for any developer in any context for fork, adapt and deploy and make the first fork back to the Kantara GitHub organization where it either stay in sync with this independent open source repository or can take a different direction, at the discretion of Kantara. At least now, you have one clean, understandable and usable resource all in a single repository, a single authoritative base of code, everything is correctly cross-linked, documented and completely replicable.  This is far from the state of affairs at the time Massachusetts Legal Hackers took this project on.  Puzzling out from the Kantara project we started with based questions like where the code and other assets could be found, how things were connected, which versions were correct or interoperable and other key information was quite  challenge.  To keep the project in the good shape it is now in, please maintain this repository and project in sync with the Open Innovation Network project structure and collaboration method.   In particular, if you hire more developers, use the scope of work and project plan approach to defining the expected deliverables and the issues, wiki and repo "code reviews" to ensure the project is on course and delivered well.

**Comment by dazzaji** [comment]
also... check out the beauty at: http://consentreceipt.org/

![screen shot 2015-12-11 at 7 08 08 am](https://cloud.githubusercontent.com/assets/2357755/11743506/1496e896-9fd6-11e5-95a8-8918bbcbbfcb.png)

**Comment by dazzaji** [comment]
@smartopian  did we agree this issue is now closed?

**Comment by smartopian** [comment]
thanks,  just one question first .  

in regards to: 
"Please maintain this repository and project in sync with the Open Innovation Network project structure and collaboration method. "

Is there a doc on the Open Innovation Network Project Structure?

**Comment by dazzaji** [comment]
For your purpose - make it this simple: Just don't monkey with the working repository, as delivered.
