### ISSUE TITLE
Update domain to dev.consentreceipt.com 

### ISSUE THREAD

**Issue by dazzaji** [OpenConsent/ConsentReceipt#14]
The idea is to point ConsentReceipt.org to Kantara wordpress blog and
- Point OpenConsent.org to this Dev Repo.

**Comment by smartopian** [comment]
Did you purchase consentreceipt.com?

**Comment by dazzaji** [comment]
Unfortunately I did not. Do we need to start investigating to discover who has this domain?

---

   |   Daniel "Dazza" Greenwood, JD
   |   Personal: DazzaGreenwood.com
   |   Consulting Service: CIVICS.com
   |   MIT Research: Law.MIT.edu
   |     Email: dazza@CIVICS.com
   |     Mobile: 617.500.3644
