### ISSUE TITLE
Finish button demo install.  

### ISSUE THREAD

**Issue by smartopian** [OpenConsent/ConsentReceipt#17]
At this link http://consentreceipt.openconsent.org/CRClient/ClientToCR.html the button was not installed.  
- need to finish install, or use example from install for consent receipt.org. 
  Ran into issue with the instructions.  Need to restart.

**Comment by dazzaji** [comment]
You have a working example - unless you changes it - at openconsent. Link to that. Fork the repo to Kantara for purposes of having a copy there.  Deploy API on the Kantara or other sites on a non-emergency fast turn around basis when you have resources to do that. I will fork and deploy it at an MIT repo over the next few days or maybe weeks. You can consider the time for emergency immediate turn around web development over.

**Comment by dazzaji** [comment]
This is working now - evidently the issue was syntax of main.js.
