### ISSUE TITLE
Fork ConsentReceipt To Kantara

### ISSUE THREAD

**Issue by dazzaji** [OpenConsent/ConsentReceipt#4]

**Comment by smartopian** [comment]
1. fork the repository, 
2. new repository should be consentreceipt.org and the the orignal repository should be openconsent.org

**Comment by dazzaji** [comment]
1. fork the repository to https://github.com/KantaraInitiative, 
2. point consentreceipt.org to new repository at https://github.com/KantaraInitiative and 
3. point the openconsent.org to the orignal repository at https://github.com/OpenConsent/ConsentReceipt
